#!/usr/bin/env python3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HTML = ROOT / "task-manager.html"
CSS_DIR = ROOT / "css"
JS_DIR = ROOT / "js"


def require(condition, message):
    if not condition:
        raise AssertionError(message)


def _read_bundle() -> str:
    parts = [HTML.read_text(encoding="utf-8")]
    if CSS_DIR.is_dir():
        for path in sorted(CSS_DIR.glob("*.css")):
            parts.append(path.read_text(encoding="utf-8"))
    if JS_DIR.is_dir():
        for path in sorted(JS_DIR.glob("*.js")):
            parts.append(path.read_text(encoding="utf-8"))
    return "\n".join(parts)


def main():
    # After the round-3 split, JS/CSS live in separate files. Static substring
    # checks below should still cover the full deployable bundle, so we
    # concatenate task-manager.html + css/app.css + js/*.js as a single blob.
    html = _read_bundle()
    execution_js = (JS_DIR / "execution.js").read_text(encoding="utf-8")
    require("<title>功夫豆测试平台</title>" in html, "Browser title must use 功夫豆测试平台")
    require("Midscene Task 管理平台" not in html and "Midscene Task 管理" not in html, "Old product title must not appear in the UI")
    require('<span class="header-logo">⚡</span>' not in html and '<div class="login-logo">⚡' not in html, "Old lightning emoji brand logo must not be used")
    require("brand-mark" in html and "header-subtitle" in html, "New platform brand logo/header structure is missing")
    require("assets/brand/kongfudou-icon.png" in html and "brand-mark-img" in html, "Kongfudou brand image must be used instead of a text placeholder")
    require("Qwen · Midscene · Sonic" in html, "Header subtitle must show core platform integrations")
    require("用例资产" in html, "Sidebar must include 用例资产 entry")
    # Sidebar has 5 nav groups with sub-items
    require(html.count('class="nav-group"') == 5, "Sidebar must include five nav groups (Agent/用例/执行/报告/配置)")
    require('data-nav-group="agent"' in html and 'data-nav-group="cases"' in html and 'data-nav-group="run"' in html and 'data-nav-group="report"' in html and 'data-nav-group="settings"' in html, "Sidebar nav groups must include agent/cases/run/report/settings")
    require("Agent 工作台" in html, "Dashboard must serve as the Agent workbench entry")
    require(("AI修复" in html or "AI 修复" in html) and 'data-workflow="repair"' in html, "Sidebar must expose independent AI repair entry")
    require("const AI_GATEWAY_BASE = '/ai-gateway'" in html, "AI Gateway calls must use same-origin reverse proxy")
    require("const USERS" not in html and "sonic2026" not in html and "test123" not in html, "Frontend must not contain plaintext login credentials")
    require("/auth/login" in html and "/auth/me" in html and "/auth/logout" in html, "Frontend login must use backend auth endpoints")
    require("sessionToken" in html and "Authorization" in html and "Bearer" in html, "Frontend API calls must carry Bearer session token")
    require("// ===== API CLIENT =====" in html and "async function apiRequest" in html and "async function aiRequest" in html, "Unified API client block is missing")
    require("window.fetch =" not in html, "Frontend must not monkey patch global window.fetch")
    require("async function apiTextRequest" in html and "function forceLogoutWithMessage" in html, "API client must include text requests and forced logout handling")
    require("forceLogoutWithMessage" in html and "res.status === 401" in html, "apiRequest must force logout on 401")
    require("fetch(`${API_BASE}" not in html, "Task backend calls must use apiRequest/apiTextRequest, not direct fetch(API_BASE)")
    require("api.highwayapi.ai" not in html and "127.0.0.1:8090" not in html, "Frontend must not call HighwayAPI or local gateway directly")
    require("HIGHWAY_API_KEY" not in html and "your_highway_api_key" not in html, "Frontend must not contain API key placeholders")
    require("测试当前策略" in html and "/ai/providers/test" in html, "Config page must expose AI model service test action")
    require("模型配置" in html and "/ai/providers" in html and "/ai/model-router" in html, "Config page must expose multi-provider model routing")
    require("loadAgentModelOptions" in html and "AI Gateway Provider" in html, "Agent model selector must load AI Gateway providers")
    require("modelProviderId" in html and "aiProviderId" in html and "selectedAgentModelInfo" in html, "Agent payload must keep provider id separate from raw model name")
    require("自动（按模型策略" in html, "Agent model selector must make the router-backed auto model visible")
    for label in ("生成测试用例模型", "生成 YAML 模型", "失败分析模型", "YAML 修复模型", "Agent 判断模型", "飞书缺陷草稿模型"):
        require(label in html, f"Model config label missing: {label}")
    require("测试当前策略" in html and "保存模型策略" in html, "Model config actions are missing")
    require("HIGHWAY_API_KEY" not in html and "QWEN_API_KEY" not in html, "Frontend must not contain model API key env names")
    require("AI分析失败原因" in html and "/ai/analyze-failure" in html, "Failed jobs must support AI failure analysis")
    require("生成修复 YAML" in html and "/ai/optimize-yaml" in html, "AI failure result must support YAML repair draft generation")
    require("修复后的 YAML 只作为草稿展示" in html and "不会自动覆盖当前文件或基线" in html, "YAML repair must be manual-confirm only")
    require("let repairDrafts = []" in html, "Frontend must keep repair draft state")
    for fn in ("createRepairDraftFromAiResult", "upsertRepairDraft", "currentRepairDraft", "repairDraftStatusText", "buildPendingActions"):
        require(fn in html, f"Frontend missing repair draft function: {fn}")
    require("/repair-drafts/apply" in html and "confirmApply" in html and "confirmRisk" in html, "Repair draft apply must be explicit manual confirmation")
    require("人工确认替换" in html and "拒绝草稿" in html and "待我处理" in html, "Repair drafts must surface as pending manual actions")
    require("JSON.stringify(job)" not in html, "Pending actions must not rely on string matching whole job JSON")
    # Full-auto Agent workbench checks
    require("启动 Agent" in html and "Agent 状态" in html and "Agent 产物" in html, "Full-auto Agent workbench sections are missing")
    require("AUTO_SAFE" in html and "FULL_AUTO" in html, "AI Agent mode selector must support AUTO_SAFE and FULL_AUTO")
    require("agent-mode" in html and "AUTO_SAFE" in html, "AI Agent mode radio buttons are missing")
    require("autoOverwriteBaseline: false" in html, "Agent payload must not enable auto baseline overwrite")
    require("WAIT_CONFIRM_RUN" in html and "WAIT_CONFIRM_BUG" in html, "AI Agent confirmation states are missing")
    require("确认打印" in html and "覆盖基线" in html, "AI Agent risk keywords must be present")
    require("POST /agent/run" not in html, "UI should call Agent endpoints without exposing implementation text in visible copy")
    require("/agent-runs" in html and "/agent-runs/" in html, "AI Agent endpoint calls are missing")
    require("Agent 状态" in html and "运行轨迹" in html, "Right panel must become Agent status panel with timeline")
    require("还没有选择运行记录" in html and "启动新任务后，本次步骤时间线会显示在这里" in html, "Agent workbench must default to new-run mode instead of showing the last run")
    require("return normalizeAgentRun(agentCurrentRun || null)" in html and "agentCurrentRun = agentRuns[0]" not in html, "Loading Agent history must not auto-select the latest run")
    require("copyAgentArtifact" in html and "downloadAgentYaml" in html and "downloadAgentMindmap" in html and "下载脑图" in html, "Agent artifacts must support copy plus YAML and mindmap download")
    require("agentGeneratedCaseArtifact" in html and "artifactHasValue(artifacts.matchedCases)" not in html and "Array.isArray(artifacts.matchedCases) && artifacts.matchedCases.length" in html, "Agent case artifact rendering must not treat an empty matchedCases array as real output")
    require("agentYamlArtifactPayload" in html and "agentYamlRefsFromArtifacts" in html and "本次 YAML 已按单用例拆分保存" in html, "Agent YAML artifact rendering must show split yamlRefs instead of only generatedYaml")
    require("apiTextRequest(`/file?module=" in html and "chunks.join('\\n\\n---\\n\\n')" in html, "Agent YAML download must fetch split YAML file contents when generatedYaml is empty")
    require("renderAgentReportArtifact" in html and "renderAgentSummaryArtifact" in html and "executionReports" in html and "yamlExecutionRefs" in html, "Agent report/summary artifacts must render as readable rich cards")
    require("agentCaseLabel" in html and "report-case-link" in html and "生成时参考的历史步骤" in html, "Agent reports must show the concrete case name and YAML reference examples")
    require("agentInputSummaryFromRun" in html and "agentInputSummaryHtml" in html and "本次输入资料" in html, "Agent history/detail pages must show the original target, Figma, files, and execution input")
    require("agent-input-chips" in html and "采用的 Figma 页面" in html and "上传资料" in html, "Agent input summary must be readable in cards instead of only showing runId")
    require("质量检查" in html and "renderAgentQualityArtifact" in html and "agent-quality-layers" in html and "完整用例、自动化 YAML、人工用例、Figma 图片" in html, "Agent quality report must render as readable layered cards")
    require("renderVisualReferenceReport" in html and "图片参考" in html and "上传截图" in html and "AI 判断" in html and "硬门禁" in html, "Agent quality report must show screenshot references and AI judgment status")
    require("agentInfoGrid" in html and "agentReadableList" in html and "agent-readable-panel" in html and "final-report-hero" in html, "Agent step details and final report must use readable card layouts")
    require("key === 'DONE' && runTerminal" in html and "前序步骤失败，Agent 流程未进入完成态" in html, "Agent terminal timeline must not leave the virtual DONE step pending after failure/cancel")
    require("renderGenerateYamlDetail" in html and "完整 YAML 生成主链" in html and "主链错误" in html, "Agent YAML generation step must show readable pipeline details")
    require("normalizeAgentReportArtifacts" in html and "isAgentYamlRef" in html and "normalizedAgentReportCounts" in html and "agentReportLooksYaml" in html, "Agent report rendering must not count YAML files as HTML execution reports")
    require("YAML 校验失败时，不能显示" not in html, "Implementation details should not be visible as instructional UI text")
    # Assets entry exists in sidebar as asset center
    require("用例资产" in html and 'data-workflow="assets"' in html, "Assets must be accessible from sidebar")
    require("function showAssetsCenter" in html and "assets-table" in html and "选择当前列表" in html, "Assets page must render a full-width asset table")
    require("toggleCurrentAssetRows" in html and "assetFileOp" in html and "deleteAssetFile" in html, "Assets page must support select-all, rename, move, and delete without leaving the directory")
    require("重命名</button>" in html and ">移动</button>" in html and ">删除</button>" in html, "Assets table rows must expose maintenance actions")
    require("function updateWorkbenchPanelMode" in html and "hide-jobs" in html and "'execute'" in html and "'repair'" in html, "Only Agent and execution workflows should keep the right status panel")
    require("'repair',\n    'reports'" not in html and "'repair', 'reports'" not in html, "Report and asset-style pages should not keep a stale Agent side panel")
    require("你想让 Agent 测什么" in html and "启动全自动 Agent" in html, "Dashboard hero must present the simplified Agent workbench")
    require("showModelConfigCenter" in html and "查看模型策略" in html, "Dashboard must link to model config")
    require("dashboard-accordion" in html, "Secondary dashboard cards must be collapsible")
    require("dashboard-primary-panel" in html and "dashboard-stack" in html, "Dashboard must separate primary next action from secondary details")
    require("async function copyText(text)" in html, "copyText function is missing")
    require("navigator.clipboard.writeText" in html, "copyText must try Clipboard API first")
    require("document.execCommand" in html, "copyText must include execCommand fallback for HTTP/permission failures")
    require("textarea.setSelectionRange" in html, "copyText fallback must select all text before copying")
    require("复制检查点" in html, "report checkpoint copy button text is missing")
    require("reportCheckpointText" in html, "report checkpoint text builder is missing")
    require("reviewYamlExecutabilityHtml" in html, "YAML executability panel is missing")
    require("function yamlDisplayName(file)" in html, "YAML display-name fallback is missing")
    require("replace('.yaml','')" not in html, "Do not strip YAML suffix inline; use yamlDisplayName()")
    require('replace(".yaml","")' not in html, "Do not strip YAML suffix inline; use yamlDisplayName()")
    require("高级：Figma 扫描范围" in html, "Figma advanced scan controls must be collapsed and clearly named")
    require("最多扫描 UI 页面数，不是生成用例数量" in html, "Figma limit tooltip must clarify it is not case count")
    require("用例条数由需求复杂度、风险、边界和异常覆盖自动分析" in html, "YAML generation form must explain case count is automatic")
    require(html.count("Figma 只作为本次生成 YAML 的临时 UI 参考") == 1, "Figma generation hint must not be duplicated")
    require("grid-template-rows: auto minmax(0, 1fr)" in html, "Sonic sync panel must let the list fill remaining height")
    require("下方可滚动查看全部" in html, "Sonic sync summary must tell users the list is scrollable")
    require(".sonic-preview-list" in html and "max-height: none" in html, "Sonic sync list must not be capped to three visible rows")
    submit_marker = "生成任务已提交，已切到生成记录查看进度"
    close_marker = "closeModal('modal-generate');"
    jobs_marker = "await showGenerateJobsCenter();"
    require(submit_marker in html, "Generate modal must tell the user that the background job was submitted")
    require(close_marker in html and jobs_marker in html, "Generate modal must close and switch to generation records after job creation")
    require(html.index(close_marker, html.index(submit_marker)) < html.index(jobs_marker, html.index(submit_marker)), "Generate modal must close before showing generation records")
    require("function jobDurationText(job)" in html, "Generation records must display elapsed generation time")
    require("function jobTimingText(job)" in html, "Generation job details must include start/end/duration timing")
    require("耗时" in html and "已用时" in html, "Generation duration labels must be user friendly")
    require("function jobTimelineHtml(job)" in html and "进度流水" in html, "Execution job detail must show progress timeline")
    require("单条/多条调试" in html and "multiple size=\"8\"" in html, "Execution modal must support selecting one or multiple tasks")
    require("不会触发 Sonic 测试套整套回归" in html and "每个任务只下发选中的一个 task" in html, "Single/multi-task execution must clearly state it does not run the full Sonic suite")
    require("Sonic 只负责已同步基线的测试套回归" in html, "Execution page must distinguish Runner debugging from Sonic suite regression")
    require("Sonic 维护" in html and "日常同步请在「用例资产」" in html and "清理可匹配旧步骤" in html, "Sonic maintenance page must clearly distinguish maintenance from normal YAML sync")
    require("刷新桥接脚本" in html and "refreshSonicBridgeScripts" in html, "Sonic config must expose one-click bridge script refresh")
    require("apiRequest('/sonic/refresh-bridges'" in html, "Bridge script refresh must call backend through apiRequest")
    require("不修改 YAML、不改基线、不触发执行" in html, "Bridge refresh confirmation must clearly distinguish it from YAML sync/execution")
    require("renderSonicPublishResult" in html and "单条用例同步结果" in html and "模块同步结果" in html, "Sonic publish must show explicit single/batch sync results")
    require("AI分析失败" in html and "生成修复 YAML" in html, "Dashboard must expose primary Agent and repair actions")
    require("Runner 进度" in html and "待我处理" in html and "Runner 当前任务" in html, "Execution right panel must focus on Runner progress")
    require("执行前设备检查" in html and "renderRunnerDevicePreflightCards" in html and "runner-preflight-card" in html and "runnerDeviceVersionLabel" in html, "Execution center must show Runner device/app preflight before install or run")
    require("function executionYamlRows" in html and "execution-yaml-table" in html, "Execution debug center must render an inline YAML table")
    require("选择要调试的 YAML" in html and "单条调试" in html and "整文件执行" in html, "Execution debug center must expose concrete run actions")
    require("selectExecutionModule" in html and "execution-yaml-search" in html, "Execution debug center must support module and YAML filtering")
    require("展开用例树" not in html and "查看 YAML 列表" not in html, "Execution debug center must not keep dead library-toggle actions")
    require("同步至 Sonic 平台" in html and "Sonic 同步" not in html and "Sonic同步" not in html and "设备同步" not in html, "Sonic sync UI copy must use 同步至 Sonic 平台")
    require("publishSelectedFilesToSonic" in html and "publishSonicBatchItems" in html and "同步当前已选至 Sonic 平台" in html and "selectedSonicFilesForCurrentFilters" in html, "Sonic batch sync must only publish selected YAML files from the current asset filter")
    require("await loadModules({force: true})" in html and "loadModules({force:true})" in html, "Sonic publish and asset refresh must force reload modules and sonic case rows")
    require("row.step_state === 'bridge'" in html and "(row.sonic || {}).step_state === 'bridge'" in html, "Asset Sonic status must treat bridge step state as synced")
    require("请求返回业务失败" in html and "请求失败：HTTP ${res.status}" in html and "HTTP 200" not in html, "API business failures must not be surfaced as HTTP 200 errors")
    require("function jobRunModeText" in html and "function markJobHandled" in html and "manual_confirmed" in html, "Runner side panel must label run mode and let users clear handled failures")
    require("function isRunnerExecutionJob" in html and "locallyHiddenRunnerJobIds" in html and "/^(gen|figma|mindmap|repair)_/i" in html, "Runner side panel must filter background/generated jobs and stale handled ids")
    require("activeWorkflow === 'assets'" in html and "selectedAssetRowsForCurrentFilters().map" in html, "Asset batch move/delete must use the current filtered selection")
    require("ASSET_PAGE_SIZE" in html and "MODULE_DIRECTORY_PAGE_SIZE" in html and "paginationHtml" in html and "setAssetListPage" in html, "Long YAML asset lists must render with pagination")
    require("取消任务" in html and "基线回归" in html and "调试执行" in html, "Runner side panel must expose cancel action and distinguish baseline from debug runs")
    require("取消运行" in html and "cancelAgentRunById" in html, "Agent confirmation cards must allow cancelling without entering the run detail")
    require("const canCancel = !agentRunIsTerminal(run)" in html and "canCancel ? `<button class=\"btn-sm danger\"" in html, "Running Agent history cards must expose direct cancellation")
    require("normalizeFailureAnalysis" in html and "SCRIPT_ISSUE" in html and "PRODUCT_BUG" in html and "ENV_ISSUE" in html and "UNKNOWN" in html, "AI repair must normalize and gate failure types")
    require("AI修复工作台" in html and "失败任务列表" in html and "结构化分析" in html and "YAML 修复草稿" in html, "AI repair must be an independent three-column workspace")
    require("原始 YAML" in html and "修复 YAML" in html and "Diff / 校验" in html, "YAML repair draft must show original, fixed, diff, and validation")
    require("/analyze-failure" in html and "used_full_logs" in html and "Runner 完整日志" in html, "Failed-job AI analysis must prefer backend full runner logs")
    require("function renderRepairDraftDetail" in html and "修复方式" in html and "AI 调用" in html and "使用的失败日志" in html and "修复草稿文件" in html, "Agent timeline must explain repair draft source, AI usage, target drafts, and failure evidence")
    require("function renderRerunDetail" in html and "重跑映射" in html and "重跑任务清单" in html and "function renderLearningDetail" in html and "沉淀内容" in html and "学习明细" in html, "Agent timeline must show safe-rerun progress and learning contents")
    require("执行前 dry-run" in html and "dry-run 拦截明细" in html and "YAML dry-run 结果" in html, "Agent timeline must expose dry-run checks and blockers")
    require("failureReason" in html and "failureType" in html and "失败类型：" in html, "Agent final report must show concrete Runner failure reasons")
    require("PRODUCT_BUG 不允许" not in html, "Implementation details must not leak as rough internal copy")
    require("apiRequest('/reports/cleanup'" in html and "apiRequest('/cases/mindmap-only-async'" in html and "apiRequest('/ui/generate-yaml-async'" in html, "Long-running write endpoints must use apiRequest")
    forbidden_write_patterns = [
        "fetch(`${API_BASE}/sonic/publish-batch`",
        "fetch(`${API_BASE}/file/restore`",
        "fetch(`${API_BASE}/baseline/page-refs`,",
        "fetch(`${API_BASE}/run-request`",
        "fetch(`${API_BASE}/knowledge/page`,",
        "fetch(`${API_BASE}/ui/generate-yaml-async`",
        "fetch(mindmapDownloadUrl(caseSetId), { method:"
    ]
    for pattern in forbidden_write_patterns:
        require(pattern not in html, f"Write API must use apiRequest, found direct fetch pattern: {pattern}")
    require("path-rail" in html and "失败分析：Qwen Plus" in html, "Dashboard must show model strategy as visual nodes")
    require("generation-flow" in html and "读资料" in html and "生成 YAML" in html, "Generation records must show a visual generation flow")
    require("nav-group" in html and "配置" in html, "Sidebar navigation must use five task-oriented groups")
    require("setActiveWorkflow('config');\n  renderTaskAppModal();" not in html, "App config modal must not reset workflow back to model config")
    require("setActiveWorkflow('config');\n  document.getElementById('toolbar-path').innerHTML = '<span>📁</span> 环境体检';" not in html, "System preflight must not reset workflow back to model config")
    require("['assets', 'generate', 'yaml_edit', 'execute', 'repair', 'baseline'].includes(activeWorkflow)" in html, "Opening YAML from assets/yaml_edit must preserve the current workflow")
    # Full-auto Agent specific checks
    require("startAutoAgentRun" in html and "startAgentRun" in html, "Agent run functions must be defined")
    require("agent-runs/start" in html and "agent-runs" in html, "Frontend must call backend Agent Run API")
    require("confirmAgentStep" in html and "cancelAgentRunById" in html, "Agent confirm and cancel functions must exist")
    require("agentRiskHits" in html and "classifyRiskLevel" in html, "Agent risk detection functions must exist")
    require("agent-source-type" in html and "AGENT_SOURCE_TYPES" in html, "Agent workbench must expose input source selector")
    require("renderAgentSourcePanel" in html and "collectAgentSourceRefs" in html, "Agent source panel and payload collector are missing")
    require("本次 Agent输入资料" in html and "agent-source-figma-url" in html and "agent-source-requirement-text" in html, "Agent workbench must expose Figma and requirement inputs")
    require("agent-source-file-input" in html and "handleAgentSourceFiles" in html and "handleAgentSourcePaste" in html, "Agent workbench must support requirement/screenshot upload and paste")
    require("sourceInputs: sourceMaterials" in html and "files: sourceMaterials.files" in html and "images: sourceMaterials.images" in html, "Agent payload must include uploaded source materials")
    require("renderSourceContextDetail" in html and "输入摘要" in html and "上传资料" in html and "Figma" in html and "agent-readable-panel" in html, "Agent timeline must show prepared source details and Figma extraction result")
    require("renderPlanDetail" in html and "业务分支" in html and "平台执行与门禁" in html and "Agent 启动前预览" in html and "需求显式候选（非业务路径）" in html and "AI 业务计划：尚未执行" in html, "Agent UI must keep startup candidates separate from the later AI-owned business plan")
    require("重跑后 AI 闭环" in html and "postRerunAutonomy" in html, "Agent rerun UI must expose the bounded latest-evidence repair cycle")
    require("agentFigmaPreviewItems" in html and "Figma 解析图片" in html and "agent-figma-grid" in html, "Agent Figma extraction must list parsed UI images for review")
    for source in ("manual", "requirement", "figma", "failed_job"):
        require(source in html, f"Agent source type missing: {source}")
    require("sourceType: source.sourceType" in html and "sourceRefs: source.sourceRefs" in html, "Agent payload must include sourceType/sourceRefs")
    require("agent-runner-device" in html and "renderAgentRunnerDeviceOptions" in html and "updateAgentRunnerDeviceHint" in html, "Agent workbench must expose online Runner/device selection")
    require("runnerId: runnerSelection.runner_id" in html and "deviceId: runnerSelection.device_id" in html and "deviceStrategy: runnerSelection.device_strategy" in html, "Agent payload must carry selected Runner/device strategy")
    require("selectedAgentAppPackage" in html and "appPackage," in html and "app_package: appPackage" in html, "Agent payload must carry selected app package")
    require("opt.dataset.package" in html and "runnerDeviceVersionLabel(device, appPackage)" in html, "Runner device version hint must use the selected app package")
    require("agentRunnerVersionSummary" in html and "版本：" in html and "refreshAgentRunnerDeviceByApp" in html, "Agent auto runner mode must show selected-app versions and refresh on app change")
    require("agent-start-layout" in html and "agent-form-section" in html and "agent-compact-grid" in html, "Agent start form must use grouped readable sections instead of one long form")
    require("agent-url-input" in html and "word-break: break-all" in html and "agent-device-hint" in html and "overflow-wrap: anywhere" in html, "Agent long Figma/device information must wrap and remain fully visible")
    require(".agent-field label {\n    display: inline-flex" in html and "label.agent-field > span {\n    display: inline-flex" in html and ".modal-label {\n    display: inline-flex" in html, "Agent and modal field labels must use highlighted label chips")
    require(".form-group label {\n    display: inline-flex" in html and ".figma-limit-field span {\n    display: inline-flex" in html, "Login and advanced Figma field labels must use highlighted label chips")
    require("agent-start-button" in html and "agent-action-buttons" in html and "openAgentAppInstall" in html, "Agent primary actions must stay explicit and clickable after layout optimization")
    require("DEFAULT_AGENT_APP_NAME" in html and "appendAgentAppOptions" in html and "智小白3D APP" in html, "Agent app selectors must default to 智小白3D APP even before /api/apps finishes")
    require("shouldHydrateRuns" in html and "ensureAgentRunsLoaded({ limit: 10 }).then" in html, "Agent workbench must render before background history refresh completes")
    require("agent-source-upload-copy" in html and "添加需求资料" in html and "添加资料" in html, "Agent source upload area must be visually obvious and actionable")
    require("loadRunnerDevices({force: true, quiet: true})" in html and "自动选择在线设备（推荐）" in html, "Agent workbench must load online Runner devices without re-rendering the whole dashboard")
    require("if (sourceType === 'manual')" in html and "hasFiles" in html and "sourceType = 'requirement'" in html and "sourceType = 'figma'" in html, "Agent frontend must promote manual source type when files or Figma are attached")
    require("executionMode: 'RUNNER_JOB'" in html, "Agent payload must default to Runner job execution instead of Sonic suite execution")
    require("输入来源：" in html and "整理输入来源" in html, "Agent preview/timeline copy must explain source preparation")
    require("${AGENT_TIMELINE_STEPS.length} 个处理步骤" in html and "['PREPARE_SOURCE', '整理输入来源']" in html, "Agent timeline must use dynamic count and include PREPARE_SOURCE")
    require("14 步全自动链路" not in html, "Agent timeline copy must not hard-code stale step count")
    require("timelineLiveTraceDetail" in html and "step-live-trace" in html, "Agent timeline must show live running trace when a step is expanded")
    require("renderExecutionPrecheckDetail" in html and "precheck-warnings" in html and "blockers" in html, "Execution precheck detail must show blockers and warnings")
    require("match-keywords" in html and "匹配关键词" in html and "detail.reasons" in html, "Agent match detail must show concrete matched keywords and candidate reasons")
    require("renderAgentHistoryPage" in html and "Agent 运行记录" in html, "Agent history menu must render a dedicated history page")
    require("agentRunErrorHtml" in html and "无法加载 Agent 运行记录" in html and "请求超时，请稍后重试" in html, "Agent history refresh must show an error/retry state instead of staying in loading")
    require("agentHistoryRequestSeq" in html and "activeWorkflow !== 'agent_history'" in html and "timeoutMs: 15000" in html, "Agent history refresh must guard stale requests and use a bounded timeout")
    require("async function selectAgentRun" in html and "apiRequest(`/agent-runs/${encodeURIComponent(runId)}`" in html, "Agent history cards must fetch full run detail before showing timeline")
    require("deleteAgentRunById" in html and "删除记录" in html and "method: 'DELETE'" in html, "Agent terminal run history cards must allow deleting failed/completed records")
    require("agentRunsByCreatedDesc" in html and "agentRunSortTime" in html and "mergeAgentRun" in html, "Agent history updates must keep cards sorted by creation time instead of last update time")
    require("agentRunSelectionSeq" in html and "openAgentRunTrace" in html and "selectionSeq !== agentRunSelectionSeq" in html, "Agent history detail loading must ignore stale click/request races")
    require("renderAgentConfirmPage" in html and "人工确认中心" in html, "Agent confirmation menu must render a dedicated pending-confirmation page")
    require("renderActiveWorkflowPage" in html and "renderAgentHistoryPage(options)" in html and "renderAgentConfirmPage({ refresh: false" in html, "Agent refresh routing must render the current Agent sub-page instead of stale workbench content")
    require("agentRiskDetailFrom" in html and "agentRiskDetailHtml" in html and "风险来源" in html and "触发片段" in html, "Agent high-risk confirmations must show concrete source and triggering snippet")
    require("renderAgentPageAfterRunUpdate" in html and "activeWorkflow === 'agent_confirm'" in html and "activeWorkflow === 'agent_history'" in html, "Agent confirm/cancel/refresh must update the current sub-page")
    require("Runner 单条调试" in html and "/run-request" in html, "Sonic status UI must route single/multi debugging to local Runner jobs")
    require("rerunGenerationSmokeCases" in html and "/cases/rerun-smoke" in html and "重跑冒烟" in html, "Generated smoke cases must expose a rerun action without re-uploading materials")
    require("generationSmokeAdjustmentHtml" in html and "generatedSmokeRefs" in html and "冒烟用例调整" in html and "首次生成时，Agent 会自动下发" in html and "编辑 YAML" in html and "当前已保存的 YAML" in html, "Generated smoke cases must auto-run first and remain editable before rerun")
    require("GENERATED_SMOKE_RERUN_DEFAULT_LIMIT = 3" in html and "generatedSmokeTargets" in html and "generatedSmokeRerunLimit(summary" in html and "重跑首批冒烟" in html and "重跑全部冒烟" in html and "run_all" in html, "Generated smoke rerun must default to at most 3 first-batch smoke cases and require an explicit all-smoke action")
    require("继续下一批可执行" in html and "执行全部当前可执行" in html and "remaining_executable" in html, "Generated executable rerun must support small-batch continuation and explicit full execution")
    require("agentGeneratedSmokeRerunLimit" in html and "重跑首批冒烟 ${escapeHtml(smokeLimit)}/${escapeHtml(smokeExecutableCount)}" in html and "重跑冒烟${smokeExecutableCount" not in html, "Agent artifact rerun button must show first-batch count instead of total executable smoke count")
    require("expandedBatches" in html and "expandedStopReason" in html and "第 ${escapeHtml(batch.batch || '-')} 批" in html, "Agent final report must expose expanded execution batches instead of looking smoke-only")
    require("runSonicSingleCase" not in html and "/sonic/run-case" not in html and "Sonic 临时套执行" not in html, "Frontend must not expose Sonic temporary-suite single-case execution")
    require("Trace 回放" in html and "/debug/traces" in html and "/debug/replay" in html and "/debug/diff" in html, "Execution center must expose Trace replay/diff debugger")
    trace_viewer = (ROOT / "trace-viewer.html").read_text(encoding="utf-8")
    require("Execution Trace Viewer" in trace_viewer and "/debug/traces" in trace_viewer and "sessionToken" in trace_viewer, "Trace viewer must render real trace data with session auth")
    require("一键应用推荐策略" in html and "applyRecommendedStrategy" in html, "Model config must support one-click recommended strategy")
    require("deleteGenerationMindmapRecord" in html and "/cases/mindmap-record" in html and "删除记录" in html, "Mindmap center must support deleting generation records")
    require("uploadApkInChunks" in execution_js and "/app-install/upload-chunk" in execution_js and "/app-install/upload-finish" in execution_js, "APK install uploads must use chunk upload endpoints")
    require("readAsDataURL(file)" not in execution_js and "contentBase64: dataUrl.split" not in execution_js, "APK install uploads must not send the whole APK as one Base64 JSON body")
    require("js/execution.js?v=20260701-install-refresh" in html and "js/app.js?v=20260701-smoke-dynamic" in html and "js/agent-workbench.js?v=20260701-smoke-dynamic" in html and "js/agent-status.js?v=20260702-agent-artifacts" in html, "Frontend cache version must be bumped for install refresh, smoke rerun, and Agent artifact updates")
    require("function jobDeviceLabel" in html and "runnerDevices" in html and "runnerDeviceDisplayName(device)" in html, "Job rows must resolve device ids to public runner device names when available")
    require("handleApkInstallJobsUpdated" in html and "loadRunnerDevices({force: true, quiet: true})" in html and "previousJobs" in html and "[0, 3000, 8000]" in html, "APK install completion must refresh runner devices and app versions automatically")
    require("closeMindmapCreateModal(options = {})" in html and "#modal-mindmap-create .modal-close, #modal-mindmap-create .btn-cancel" in html, "Mindmap create modal must remain closable while background generation is running")
    require("脑图生成任务已提交，已切到脑图中心查看进度" in html and "closeMindmapCreateModal({ quiet: true })" in html and "await showMindmapCenter();" in html, "Mindmap create modal must auto-close after background job submission")
    require("function isMindmapBackgroundJob" in html and "mindmapTaskSectionHtml" in html and "mindmapFilesSectionHtml" in html, "Mindmap center must render background task status separately from downloadable files")
    require("generation-record-sections" in html and "脑图生成任务" in html and "脑图文件" in html, "Mindmap center must split task progress and mindmap files into readable sections")
    require("function mindmapRecordTimeValue" in html and "mindmap_sort_ts" in html and "mindmap-compact-list" in html and "function mindmapTaskRow" in html, "Mindmap center must sort latest first and use compact rows instead of oversized cards")
    require("activeWorkspaceMode === 'mindmap'" in html and "await showMindmapCenter();" in html, "Mindmap background actions must refresh the mindmap center after cancel/retry")
    require("mindmapCenterRefreshTimer" in html and "scheduleMindmapCenterRefresh(taskRows)" in html and "pending', 'running" in html, "Mindmap center must auto-refresh while mindmap jobs are active")
    print({"ok": True, "file": str(HTML), "checks": 65})


if __name__ == "__main__":
    main()
