<script setup lang="ts">
import {computed,reactive,ref,watch} from 'vue'
import type {LoadRun} from '../api/contracts'
import {performanceBaselinesApi,type PerformanceBaseline,type RegressionPolicy,type BaselineRegression} from '../api/loadPerformanceBaselines'
import {apiTestingHasPermission} from '../utils/authRedirect'
const props=defineProps<{runs:LoadRun[];projectId:string}>()
const items=ref<PerformanceBaseline[]>([]),loading=ref(false),busy=ref(false),error=ref(''),notice=ref(''),truncated=ref(false),adopting=ref(false)
const selectedId=ref(''),candidateId=ref(''),result=ref<BaselineRegression>()
let scopeRequest=0,comparisonRequest=0
const form=reactive({run_id:'',name:'性能参考基线',adoption_reason:'',p95:true,p95_limit:10,rps:true,rps_limit:10,http:true,http_limit:1,business:false,business_limit:1})
const canManage=computed(()=>apiTestingHasPermission('api.baseline')&&apiTestingHasPermission('api.loadtest.view'))
const completed=computed(()=>props.runs.filter(run=>run.project_id===props.projectId&&run.state==='finished'&&run.finished_at))
const selected=computed(()=>items.value.find(item=>item.id===selectedId.value))
const candidates=computed(()=>completed.value.filter(run=>run.id!==selected.value?.source_run_id))
const valid=computed(()=>form.run_id&&form.name.trim()&&form.adoption_reason.trim()&&(form.p95||form.rps||form.http||form.business))
function runLabel(run:LoadRun):string {return `${String((run.configuration.scenario as Record<string,unknown>|undefined)?.name||'执行')} · ${String((run.configuration.test_context as Record<string,unknown>|undefined)?.release||'版本未记录')} · ${run.id.slice(0,8)}`}
function value(actual:number|null|undefined,unit=''):string{return actual==null?'—':`${actual.toLocaleString('zh-CN',{maximumFractionDigits:3})} ${unit}`}
async function refresh():Promise<void>{
 const seq=++scopeRequest;error.value='';loading.value=true
 if(!props.projectId){items.value=[];loading.value=false;return}
 try{const response=await performanceBaselinesApi.list(props.projectId);if(seq===scopeRequest){items.value=response.baselines;truncated.value=response.truncated;if(!items.value.some(item=>item.id===selectedId.value))selectedId.value=items.value.find(item=>item.status==='active')?.id||items.value[0]?.id||''}}
 catch(e){if(seq===scopeRequest)error.value=e instanceof Error?e.message:'参考基线读取失败'}finally{if(seq===scopeRequest)loading.value=false}
}
watch(()=>props.projectId,()=>{items.value=[];selectedId.value='';candidateId.value='';form.run_id='';form.adoption_reason='';result.value=undefined;adopting.value=false;notice.value='';comparisonRequest++;void refresh()},{immediate:true})
watch([selectedId,candidateId],()=>{result.value=undefined;comparisonRequest++})
async function adopt():Promise<void>{
 if(!canManage.value||!valid.value||busy.value)return
 busy.value=true;error.value='';notice.value='';const project=props.projectId
 const policy:RegressionPolicy={...(form.p95?{p95_increase_percent:form.p95_limit}:{}),...(form.rps?{rps_decrease_percent:form.rps_limit}:{}),...(form.http?{http_error_increase_points:form.http_limit}:{}),...(form.business?{business_failure_increase_points:form.business_limit}:{})}
 try{const created=await performanceBaselinesApi.adopt({run_id:form.run_id,name:form.name.trim(),adoption_reason:form.adoption_reason.trim(),regression_policy:policy});if(project===props.projectId){adopting.value=false;await refresh();if(project===props.projectId){selectedId.value=created.id;notice.value='采纳记录已保存。原参考记录保留为历史，条件与预警阈值已冻结。'}}}
 catch(e){if(project===props.projectId)error.value=e instanceof Error?e.message:'采纳失败'}finally{busy.value=false}
}
async function retire():Promise<void>{
 if(!canManage.value||!selected.value||busy.value)return
 const id=selected.value.id,project=props.projectId;busy.value=true;error.value=''
 try{await performanceBaselinesApi.retire(id);if(project===props.projectId){await refresh();if(project===props.projectId)notice.value='已停用；历史证据仍保留，可继续手动查看对比。'}}catch(e){if(project===props.projectId)error.value=e instanceof Error?e.message:'停用失败'}finally{busy.value=false}
}
async function compare():Promise<void>{
 if(!selectedId.value||!candidateId.value||busy.value)return
 const seq=++comparisonRequest;busy.value=true;error.value=''
 try{const response=await performanceBaselinesApi.compare(selectedId.value,candidateId.value);if(seq===comparisonRequest)result.value=response}
 catch(e){if(seq===comparisonRequest)error.value=e instanceof Error?e.message:'退化核对失败'}finally{busy.value=false}
}
</script>
<template>
<section class="performance-baselines" aria-label="性能参考基线">
 <header><div><h2>性能参考基线与退化预警</h2><p>人工采纳完成执行，固定当时证据。这里只做手动核对，不启用定时发压或发送通知。</p></div><button v-if="canManage" type="button" class="secondary-command" data-testid="baseline-open-adopt" :disabled="busy||!completed.length" @click="adopting=!adopting">{{ adopting?'收起采纳表单':'采纳已完成执行' }}</button></header>
 <p v-if="loading" role="status">正在读取参考基线…</p><p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p><p v-if="!loading&&!items.length">当前项目暂无性能参考基线。</p><p v-if="truncated">仅列出前 200 条参考记录，优先当前启用项。</p>
 <form v-if="adopting&&canManage" class="baseline-form" @submit.prevent="adopt"><h3>人工采纳参考执行</h3><label>来源执行<select v-model="form.run_id" data-testid="baseline-adopt-run" required><option value="">选择已完成执行</option><option v-for="run in completed" :key="run.id" :value="run.id">{{ runLabel(run) }}</option></select></label><label>参考名称<input v-model="form.name" required maxlength="160" /></label><label class="baseline-wide">采纳理由<textarea v-model="form.adoption_reason" data-testid="baseline-reason" required maxlength="2000" rows="2" placeholder="说明为什么这轮可作为性能参考，以及已核对的证据" /></label><fieldset class="baseline-wide"><legend>人工设定退化预警阈值（超过时预警）</legend><label class="baseline-check"><input v-model="form.p95" type="checkbox" /><span>P95 增幅</span><input v-model.number="form.p95_limit" type="number" min="0" max="1000" step="0.1" :disabled="!form.p95" />%</label><label class="baseline-check"><input v-model="form.rps" type="checkbox" /><span>请求吞吐降幅</span><input v-model.number="form.rps_limit" type="number" min="0" max="100" step="0.1" :disabled="!form.rps" />%</label><label class="baseline-check"><input v-model="form.http" type="checkbox" /><span>HTTP 失败率增幅</span><input v-model.number="form.http_limit" type="number" min="0" max="100" step="0.1" :disabled="!form.http" />百分点</label><label class="baseline-check"><input v-model="form.business" type="checkbox" /><span>业务断言失败率增幅</span><input v-model.number="form.business_limit" type="number" min="0" max="100" step="0.1" :disabled="!form.business" />百分点</label></fieldset><p class="baseline-wide">服务端核对节点完成、实际负载与采样完整性；证据不足不会采纳。采纳不是性能达标承诺。新参考替代同一场景和环境的当前项，旧证据与阈值保留。</p><div class="baseline-actions baseline-wide"><button type="submit" class="primary-command" data-testid="baseline-adopt" :disabled="!valid||busy">{{ busy?'正在核对并保存…':'核对证据并采纳' }}</button></div></form>
 <template v-if="items.length"><label class="baseline-select">参考记录<select v-model="selectedId" data-testid="baseline-select"><option v-for="item in items" :key="item.id" :value="item.id">{{ item.name }} · {{ item.environment_name }} · {{ item.release||'版本未记录' }} · {{ item.status==='active'?'当前':'历史' }}</option></select></label><article v-if="selected" class="baseline-summary"><header><h3>{{ selected.name }}</h3><button v-if="canManage&&selected.status==='active'" type="button" class="secondary-command" data-testid="baseline-retire" :disabled="busy" @click="retire">停用参考</button></header><p>{{ selected.scenario_name }} · {{ selected.environment_name }} · {{ selected.release||'版本未记录' }} · {{ selected.created_by }} 于 {{ new Date(selected.created_at).toLocaleString() }} 采纳</p><p>{{ selected.adoption_reason }}</p><p>冻结 P95 {{ value(selected.metrics.p95_ms,'ms') }} · 冻结请求吞吐 {{ value(selected.metrics.requests_per_second,'RPS') }}</p></article><div class="baseline-actions"><label>核对执行<select v-model="candidateId" data-testid="baseline-candidate"><option value="">选择同一场景和环境的完成执行</option><option v-for="run in candidates" :key="run.id" :value="run.id">{{ runLabel(run) }}</option></select></label><button type="button" class="primary-command" data-testid="baseline-compare" :disabled="busy||!candidateId" @click="compare">{{ busy?'正在处理…':'与参考基线核对' }}</button></div></template>
 <article v-if="result" class="baseline-result" aria-label="基线退化核对结果"><h3>{{ result.state==='regression_warning'?'退化预警':result.state==='within_reference'?'未触发已选预警':'条件或证据不足' }}</h3><p>{{ result.message }}</p><p>{{ result.notice }}</p><ul v-if="result.comparison.reasons.length"><li v-for="reason in result.comparison.reasons" :key="reason">{{ reason }}</li></ul><div class="baseline-scroll"><table><thead><tr><th>预警指标</th><th>当前变化</th><th>人工阈值</th><th>判断</th></tr></thead><tbody><tr v-for="check in result.checks" :key="check.key"><th>{{ check.label }}</th><td>{{ value(check.actual,check.unit) }}</td><td>{{ value(check.limit,check.unit) }}</td><td>{{ check.triggered==null?'无法判断':check.triggered?'超过阈值':'未超过阈值' }}</td></tr></tbody></table></div><details><summary>查看冻结参照与当前原始数值</summary><div class="baseline-scroll"><table><thead><tr><th>指标</th><th>冻结参照</th><th>当前执行</th></tr></thead><tbody><tr v-for="metric in result.comparison.metrics" :key="metric.key"><th>{{ metric.label }}</th><td>{{ value(metric.reference,metric.unit) }}</td><td>{{ value(metric.current,metric.unit) }}</td></tr></tbody></table></div></details></article>
</section>
</template>
<style scoped>
.performance-baselines{display:grid;gap:14px;min-width:0;background:#fff;border:1px solid #dbe3ee;border-radius:12px;padding:20px;margin:16px 0;color:#172b43}.performance-baselines header{display:flex;align-items:center;justify-content:space-between;gap:14px}.performance-baselines h2{font-size:20px;margin:0}.performance-baselines h3{font-size:16px;margin:0}.performance-baselines p,.performance-baselines li{font-size:13px;line-height:1.6;color:#617187;margin:6px 0}.performance-baselines label{display:grid;gap:6px;font-size:13px;min-width:0}.performance-baselines select,.performance-baselines textarea,.performance-baselines input:not([type=checkbox]){box-sizing:border-box;max-width:100%;width:100%;padding:8px;min-height:36px;border:1px solid #cbd5e1;border-radius:6px;background:#fff}.baseline-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;border:1px solid #e2e8f0;padding:16px;border-radius:8px}.baseline-wide,.baseline-form>h3{grid-column:1/-1}.baseline-form fieldset{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:12px;border:1px solid #e2e8f0}.baseline-form legend{font-size:13px}.baseline-form .baseline-check{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.baseline-check input[type=checkbox]{width:18px;height:18px;min-width:18px;flex:0 0 18px;margin:0}.baseline-check input[type=number]{width:80px}.baseline-select{max-width:720px}.baseline-actions{display:flex;align-items:flex-end;flex-wrap:wrap;gap:12px}.baseline-actions label{min-width:250px;max-width:100%}.baseline-summary,.baseline-result{border-top:1px solid #e2e8f0;padding-top:14px}.baseline-scroll{overflow:auto;margin:12px 0}.baseline-scroll table{width:100%;border-collapse:collapse;text-align:left;font-size:13px}.baseline-scroll td,.baseline-scroll th{padding:10px;border-bottom:1px solid #e2e8f0;white-space:nowrap}.baseline-scroll th{background:#f8fafc}.performance-baselines summary{font-size:13px;color:#176da5;cursor:pointer}.performance-baselines [role=alert]{color:#b91c1c}@media(max-width:700px){.performance-baselines{padding:14px}.performance-baselines header{align-items:flex-start;flex-direction:column}.baseline-form,.baseline-form fieldset{grid-template-columns:1fr}.baseline-form{padding:12px}}
</style>
