<script setup lang="ts">
import { computed } from 'vue'
import { monitoringScopeLabel } from '../utils/monitoringMetrics'
interface Point { timestamp: number; value: number | null; source_timestamp?: number | null; denominator_value?: number | null; used_value?: number | null; utilization_percent?: number | null; missing_reason?: string | null }
interface Series { labels: Record<string, string>; points: Point[] }
interface Metric { key: string; label?: string; unit?: string; denominator?: string; semantics?: string; denominator_unit?: string; used_unit?: string; series: Series[] }
interface Service { revision_id?: string; name: string; scope?: string; state: string; message?: string; source_url?: string; step_seconds?: number; metrics: Metric[] }
interface Monitoring { state?: string; terminal?: boolean; services?: Service[] }
const props = defineProps<{ monitoring?: Monitoring }>()
const services = computed(() => props.monitoring?.services || [])
const states: Record<string,string> = { collecting:'监控收集中', completed:'采集完成', partial:'部分监控缺失', failed:'监控采集失败', missing:'采样缺失', not_selected:'未选择资源监控' }
function values(s: Series): number[] { return s.points.flatMap(p => p.value != null && Number.isFinite(p.value) ? [p.value] : []) }
function peak(s: Series): number | undefined { const a=values(s); return a.length ? Math.max(...a) : undefined }
function display(v: number | undefined, unit='%'): string { if(v===undefined)return '—'; if(unit==='state')return v===1 ? '已就绪（1）' : v===0 ? '未确认就绪（0）' : '未知'; const scale=unit==='bytes' ? 1048576 : unit==='bytes/s' ? 1024 : 1; const label=unit==='bytes' ? 'MiB' : unit==='bytes/s' ? 'KiB/s' : unit==='cores' ? '核' : unit; return `${(v/scale).toLocaleString('zh-CN',{maximumFractionDigits:2})} ${label}` }
function unitLabel(unit?: string): string { return unit==='state' ? '状态 0 / 1' : unit || '' }
function axisTop(s: Series, unit?: string): number { return unit==='state' ? 1 : unit==='%' ? Math.max(100,peak(s)||0) : Math.max(1,(peak(s)||0)*1.1) }
function denominator(value?: string): string { return ({host_cpu_cores:'CPU 分母：整机全部逻辑核',host_memory_total_bytes:'内存分母：主机总内存',container_cpu_quota_cores:'CPU 分母：同一容器实测 quota / period；无限额或未知时不计算占比',filesystem_size_bytes:'空间分母：该文件系统 size_bytes',disk_operations_per_second:'延迟分母：该设备完成操作速率（IOPS）',not_applicable:'绝对用量 / 速率，无百分比分母',not_available:'未验证资源限制，只展示实际用量'} as Record<string,string>)[value || ''] || value || '统计分母未上报' }
function resource(v: number | null | undefined, unit?: string): string { return v == null ? '—' : unit==='bytes' ? `${(v/1048576).toLocaleString('zh-CN',{maximumFractionDigits:2})} MiB` : `${v.toLocaleString('zh-CN',{maximumFractionDigits:2})} ${unit === 'cores' ? '核' : unit || ''}` }
function time(v: number): string { return new Date(v*1000).toLocaleTimeString('zh-CN',{hour12:false}) }
function paths(s: Series, step=15, unit='%'): string[] {
 const first=s.points[0]?.timestamp || 0; const span=(s.points.at(-1)?.timestamp || first)-first; const top=axisTop(s,unit)
 const groups:string[]=[];let group:string[]=[]
 s.points.forEach((p,i)=>{if(p.value===null || !Number.isFinite(p.value) || (i>0 && p.timestamp-s.points[i-1]!.timestamp>step*1.5)){if(group.length)groups.push(group.join(' '));group=[]}if(p.value!==null && Number.isFinite(p.value))group.push(`${span?8+(p.timestamp-first)/span*584:300},${112-p.value/top*100}`)})
 if(group.length)groups.push(group.join(' '));return groups
}
</script>
<template>
<section class="resource-monitoring" aria-label="被测资源监控">
<header><div><h2>被测资源 · CPU、内存、Pod 状态与其他指标</h2><p>与发压节点分开统计，按本次监控配置采集。</p></div><b>{{ states[monitoring?.state || 'not_selected'] || '等待采集' }}</b></header>
<p v-if="!services.length">未选择资源监控，本次不能据此判断 CPU 或内存瓶颈。</p>
<article v-for="s in services" :key="s.revision_id || s.name"><header><h3>{{ s.name }}</h3><span>{{ states[s.state] || s.state }}</span></header><p>采集范围：{{ s.scope === 'host' || !s.scope ? '整台主机，不是单个业务服务的独占资源' : monitoringScopeLabel(s.scope) + (s.scope === 'pod_state' ? '；按 UID 和容器展示，采集目标为 kube-state-metrics' : s.scope === 'postgres' ? '；数据库事务指标不代表业务链路吞吐' : '；保留真实容器标识，不代表整个服务的汇总') }}。数据源：{{ s.source_url || '地址未上报' }}</p><p v-if="s.message">{{ s.message }}</p>
<div class="resource-grid"><section v-for="m in s.metrics" :key="m.key" class="resource-metric"><h4>{{ m.label || m.key }}（{{ unitLabel(m.unit) }}）</h4><p>{{ denominator(m.denominator) }}</p><p v-if="m.semantics">{{ m.semantics }}</p><p v-if="!m.series?.length">采样缺失，不代表使用量为零。</p>
<div v-for="(series,i) in m.series" :key="i"><strong>{{ Object.entries(series.labels).filter(([key]) => key !== '__name__').map(([key,value]) => `${key}=${value}`).join(' / ') || '实例未标识' }}</strong><p>{{ m.key === 'pod_ready' ? '最后观测状态' : m.key === 'pod_restarts_increase_2m' ? '滚动窗口峰值' : '峰值' }} <b>{{ display(m.key === 'pod_ready' ? (series.points.at(-1)?.value ?? undefined) : peak(series),m.unit) }}</b> · 有效样本 {{ values(series).length }} 条<span v-if="m.key === 'pod_ready' && series.points.length"> · 观测于 {{ time(series.points.at(-1)!.timestamp) }}；仅代表该采样时刻，不能据此判断当前是否就绪。</span></p>
<svg viewBox="0 0 600 140" role="img" :aria-label="`${m.label || m.key}资源曲线`"><line x1="8" x2="592" y1="112" y2="112" stroke="#cbd5e1"/><text x="8" y="10">{{ display(axisTop(series,m.unit),m.unit) }}</text><polyline v-for="(path,j) in paths(series,s.step_seconds,m.unit)" :key="j" :points="path" fill="none" stroke="#0891b2" stroke-width="2"/><circle v-for="(point,k) in series.points.filter(p => p.value !== null)" :key="`point-${k}`" :cx="series.points.length <= 1 ? 300 : 8+(point.timestamp-series.points[0]!.timestamp)/(series.points.at(-1)!.timestamp-series.points[0]!.timestamp)*584" :cy="112-Number(point.value)/axisTop(series,m.unit)*100" r="3" fill="#0891b2"><title>{{ time(point.timestamp) }} · {{ display(Number(point.value),m.unit) }}</title></circle><text v-if="series.points.length" x="8" y="137">{{ time(series.points[0]!.timestamp) }}</text><text v-if="series.points.length" x="592" y="137" text-anchor="end">{{ time(series.points.at(-1)!.timestamp) }}</text></svg>
<details><summary>查看时间与采样明细</summary><div class="resource-table"><table><thead><tr><th>查询时间</th><th>源采样时间</th><th>采样值（{{ unitLabel(m.unit) }}）</th><th v-if="s.scope !== 'pod_state'">资源分母</th><th v-if="s.scope !== 'pod_state'">已用资源</th><th v-if="m.key === 'cpu_cores'">占 CPU 配额</th></tr></thead><tbody><tr v-for="p in series.points" :key="p.timestamp"><td>{{ time(p.timestamp) }}</td><td>{{ p.source_timestamp == null ? '—' : time(p.source_timestamp) }}</td><td>{{ p.value===null ? (p.missing_reason === 'no_operations' ? '无 I/O，延迟不可定义' : '采样缺失') : display(p.value,m.unit) }}</td><td v-if="s.scope !== 'pod_state'">{{ resource(p.denominator_value,m.denominator_unit) }}</td><td v-if="s.scope !== 'pod_state'">{{ resource(p.used_value,m.used_unit) }}</td><td v-if="m.key === 'cpu_cores'">{{ p.utilization_percent == null ? '未知 / 无配额' : display(p.utilization_percent, '%') }}</td></tr></tbody></table></div></details></div></section></div></article>
</section>
</template>
<style scoped>
.resource-monitoring{background:#fff;border:1px solid #dbe3ee;border-radius:12px;padding:20px;margin:16px 0;color:#172b43}.resource-monitoring header{display:flex;justify-content:space-between;align-items:center;gap:16px}.resource-monitoring h2{font-size:20px;margin:0}.resource-monitoring h3{font-size:17px;margin:0}.resource-monitoring p{font-size:13px;color:#617187;line-height:1.6;margin:8px 0;overflow-wrap:anywhere}.resource-monitoring header>b{font-size:13px;color:#087f86}.resource-monitoring article{border-top:1px solid #dbe3ee;padding-top:18px;margin-top:18px}.resource-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.resource-metric{min-width:0;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px}.resource-metric h4{margin:0;font-size:15px}.resource-metric strong{font-size:13px;overflow-wrap:anywhere}.resource-metric b{font-size:19px;font-variant-numeric:tabular-nums}.resource-metric svg{width:100%;min-height:120px;font-size:10px;fill:#64748b}.resource-table{max-height:200px;overflow:auto}.resource-table table{width:100%;font-size:13px;text-align:left}.resource-table td{padding:5px}.resource-metric summary{font-size:13px;cursor:pointer;color:#176a9c}@media(max-width:900px){.resource-grid{grid-template-columns:1fr}.resource-monitoring header{align-items:flex-start;flex-wrap:wrap}}
</style>
