<script setup lang="ts">
import { computed } from 'vue'
import LoadGeneratorTrend from './LoadGeneratorTrend.vue'
const props = defineProps<{ agents: Array<Record<string, any>> }>()
const nodes = computed(() => props.agents.map(node => ({name: node.name, shard_id: node.shard_id, resource: node.load_generator_resources || {}, samples: node.load_generator_resources?.samples || []})))
const scope = (value: string) => value === 'k6_process' ? '仅 k6 进程' : value?.startsWith('cgroup') ? 'Agent 所在容器/控制组（含其子进程）' : '未采集'
function num(value: unknown, divisor = 1) { return typeof value === 'number' && Number.isFinite(value) ? (value / divisor).toLocaleString('zh-CN',{maximumFractionDigits:2}) : '—' }
function peak(samples: Array<any>, key: string) { const values = samples.map(p => p[key]).filter(v => typeof v === 'number' && Number.isFinite(v)); return values.length ? Math.max(...values) : null }
</script>
<template><section class="generator-resources" aria-label="压力机运行资源"><h2>压力机运行资源</h2><p>这是发压节点的实时运行采样，不是被测服务资源，也不是校准结果。没有采样时不能判断压力机是否成为瓶颈。</p><article v-for="node in nodes" :key="node.shard_id"><header><strong>{{ node.name }}</strong><small>{{ node.samples.length ? `${node.samples.length} 个保留样本 · 间隔 ${node.resource.interval_seconds} 秒` : '未采集 · 请检查 Agent 版本和采样状态' }}</small></header><template v-if="node.samples.length"><div class="generator-values"><div><span>CPU 峰值</span><strong>{{ num(peak(node.samples,'cpu_used_cores')) }} 核</strong><small>{{ scope(node.samples.at(-1).cpu_scope) }}</small></div><div><span>内存峰值</span><strong>{{ num(peak(node.samples,'memory_used_bytes'), 1048576) }} MiB</strong><small>{{ scope(node.samples.at(-1).memory_scope) }}</small></div><div><span>CPU 使用率峰值</span><strong>{{ num(peak(node.samples,'cpu_percent')) }} %</strong><small>{{ node.samples.at(-1).cpu_limit_source === 'cgroup_quota' ? '分母为控制组 CPU 配额' : node.samples.at(-1).cpu_limit_source === 'visible_cpus' ? '分母为可见 CPU 核数；不是独享配额' : '分母未采集，使用率未知' }}</small></div></div><div class="generator-charts"><LoadGeneratorTrend title="CPU 实际用量" unit="核" :samples="node.samples" field="cpu_used_cores" :interval="node.resource.interval_seconds" /><LoadGeneratorTrend title="内存实际用量" unit="MiB" :samples="node.samples" field="memory_used_bytes" :divisor="1048576" :interval="node.resource.interval_seconds" /></div><details><summary>查看最近 100 个采样点</summary><div class="generator-table"><table><thead><tr><th>采样时间</th><th>CPU 核数</th><th>CPU 分母</th><th>内存 MiB</th><th>内存限制 MiB</th></tr></thead><tbody><tr v-for="sample in node.samples.slice(-100)" :key="sample.sampled_at"><td>{{ new Date(sample.sampled_at).toLocaleString() }}</td><td>{{ num(sample.cpu_used_cores) }}</td><td>{{ num(sample.cpu_limit_cores) }}</td><td>{{ num(sample.memory_used_bytes,1048576) }}</td><td>{{ num(sample.memory_limit_bytes,1048576) }}</td></tr></tbody></table></div></details><p v-if="node.resource.dropped_samples">容量限制已省略 {{ node.resource.dropped_samples }} 个早期样本，峰值仅根据保留样本计算。</p></template></article></section></template>
<style scoped>.generator-resources{margin:16px 0;padding:18px;border:1px solid #dce5ee;border-radius:10px;background:white}.generator-resources h2{font-size:18px;margin:0 0 8px}.generator-resources p,.generator-resources small{font-size:13px;color:#617086;line-height:1.6}.generator-resources article{padding:12px 0;border-top:1px solid #e5ebf2}.generator-resources header{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.generator-charts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:12px 0}.generator-values{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:12px 0}.generator-values>div{display:grid;gap:4px;background:#f4f8fc;padding:12px;border-radius:8px}.generator-values span{font-size:13px}.generator-values strong{font-size:20px;color:#164c68}.generator-table{overflow:auto;max-height:300px}.generator-table table{width:100%;font-size:13px;border-collapse:collapse}.generator-table td,.generator-table th{padding:8px;text-align:left;white-space:nowrap;border-bottom:1px solid #e2e8f0}.generator-resources summary{cursor:pointer;font-size:13px;color:#176da5}@media(max-width:700px){.generator-charts,.generator-values{grid-template-columns:1fr}}
</style>
